{% set name = "mdformat-frontmatter" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdformat_frontmatter-{{ version }}.tar.gz
  sha256: 7ea52a85eaab60f67c950b43cbedccbf3172c0edd3c47448b645e510e7ea7e1a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7
    - mdformat >=0.7.0,<0.8.0
    - mdit-py-plugins
    - ruamel.yaml

test:
  imports:
    - mdformat_frontmatter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/butler54/mdformat-frontmatter
  summary: An mdformat plugin for parsing / ignoring frontmatter.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
