{% set name = "mdformat-frontmatter" %}
{% set version = "2.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdformat_frontmatter-{{ version }}.tar.gz
  sha256: c11190ae3f9c91ada78fbd820f5b221631b520484e0b644715aa0f6ed7f097ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - mdformat >=0.7.16,<0.8.0
    - mdit-py-plugins >=0.4.0
    - ruamel.yaml

test:
  imports:
    - mdformat_frontmatter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/butler54/mdformat-frontmatter
  summary: An mdformat plugin for parsing / ignoring frontmatter.
  dev_url: https://github.com/butler54/mdformat-frontmatter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
