{% set name = "mdformat-frontmatter" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdformat_frontmatter-{{ version }}.tar.gz
  sha256: a05c188ba2f483ab434b4e46e312c1a2ccf145e9ab95e3f493f8967c182ffd5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7
    - mdformat >=0.7.0,<0.8.0
    - mdit-py-plugins
    - ruamel.yaml

test:
  imports:
    - mdformat_frontmatter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/butler54/mdformat-frontmatter
  summary: An mdformat plugin for parsing / ignoring frontmatter.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
