schema_version: 1

context:
  name: mdformat-frontmatter
  version: 2.1.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mdformat_frontmatter-${{ version }}.tar.gz
  sha256: 9c9c3159c38407f47e567202749c74ce7680017516cd158c82400f015c6a01d1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=2,<4
    - pip
  run:
    - python >=${{ python_min }}
    - mdformat >=0.7.16
    - mdit-py-plugins >=0.4.0
    - ruamel.yaml >=0.15
tests:
  - python:
      imports:
        - mdformat_frontmatter
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: An mdformat plugin for parsing / ignoring frontmatter.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/butler54/mdformat-frontmatter
  repository: https://github.com/butler54/mdformat-frontmatter

extra:
  recipe-maintainers:
    - xylar
